### ISSUE TITLE
0.16 context

### ISSUE THREAD

**Issue by sidonsoft** [chrisrude/oobabot#22]
the context limits in 0.16 make ooba the equivalent of Joe Biden, I understand that this will be addressed with an update with custom configuation.  CTX length of 2048 is already just a ooba limit as there are models are are trained with 8192 ctx in mind and beyond.

**Comment by chrisrude** [comment]
Does that mean your bot profile isn't Joe Biden already? ;)

Working on a settings file now, in the meantime I'd suggest either using 0.1.5 or just building from source with the limit tweaked.

**Comment by sidonsoft** [comment]
trying to get python 3.10/poetry running at the moment not having much luck, but I did roll the bot back to 0.15 so that it at least usable.

**Comment by chrisrude** [comment]
Glad that works.  Let me know if you're still hitting poetry errors after a while.  I tried the instructions on a fresh ubuntu, but it's possible that other setups will need different steps.

**Comment by sidonsoft** [comment]
Ubuntu 23.04, maybe i need to use anaconda instead of miniconda

Installing the current project: oobabot (0.1.6)
(oobabot) itburnz@BurnZML:~/oobabot$ poetry run oobabot
The virtual environment found in /home/itburnz/miniconda3/envs/oobabot seems to be broken.
Recreating virtualenv oobabot-1GKkn1Nf-py3.10 in /home/itburnz/.cache/pypoetry/virtualenvs/oobabot-1GKkn1Nf-py3.10
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'oobabot'

**Comment by chrisrude** [comment]
I saw a similar error when I was using miniconda to create an environment but not specifically asking it to put python into it.  I don't know why, but unless I add python ahead of time, poetry gets really confused.

I'd suggest deleting your conda env, then recreating it with:
  `conda create -n oobabot python=3.10`

(the python=3.10 at the end is the magic)

Let me know if this works!

**Comment by sidonsoft** [comment]
I recreated the conda env but it still did not work, yes I had to force python=3.10 even tho it was using 3.10 anyways,  I have edited the settings.py and changed the CTX to 2048 and adjusted the line history to 30, everything seems fine for now

**Comment by chrisrude** [comment]
what distro are you running?

**Comment by sidonsoft** [comment]
Ubuntu 22.04

**Comment by chrisrude** [comment]
Config file is now working on main, token limit can be customized via oobabooga > request_params > truncation_length

**Comment by sidonsoft** [comment]
thanks, I will test it out
