### ISSUE TITLE
Could not connect to Stable Diffusion Server on Separate PC.

### ISSUE THREAD

**Issue by TheMeIonGod** [chrisrude/oobabot#29]
I am running Stable Diffusion on a separate PC from the one I am running the oobabot on. Therefore, the SD API is located at http://192.168.0.23:7900, which I know is correct because I have an SD Discord bot working on a separate computer. Opening the Text-Generation-WebUI and entering http://192.168.0.23:7900 into it works successfully.

I have tried:
http://192.168.0.23:7900
http://192.168.0.23:7900/
[http://192.168.0.23:7900]
"http://192.168.0.23:7900"

2023-05-16 23:57:58,348 INFO Oobabooga is at ws://localhost:5005
2023-05-16 23:57:58,357 INFO Connected to Oobabooga!
2023-05-16 23:57:58,357 INFO Stable Diffusion is at http://192.168.0.23:7900
2023-05-16 23:57:58,385 DEBUG Stable Diffusion: Using default sampler on SD server
2023-05-16 23:57:58,461 ERROR Could not connect to Stable Diffusion server: [http://192.168.0.23:7900]
2023-05-16 23:57:58,461 ERROR Please check the URL and try again.

**Comment by johnmoney83748932** [comment]
If you're using the config.yml file, try ws://your.ip.address.here:port
Otherwise, --stable-diffusion-url http://your.ip.address.here:port/ should work.
Can you reach it from the machine oobabot is running on, via other methods? (ping, nc, etc)

**Comment by TheMeIonGod** [comment]
> If you're using the config.yml file, try ws://your.ip.address.here:port Otherwise, --stable-diffusion-url http://your.ip.address.here:port/ should work. Can you reach it from the machine oobabot is running on, via other methods? (ping, nc, etc)

That actually worked. Why? I have no Idea since I put that same exact thing in before.

**Comment by TheMeIonGod** [comment]
Ok Now that it sees the stable diffusion it won't actually start the bot when I put --stable-diffusion-url http://192.168.0.23:7900/ into it.

**Comment by johnmoney83748932** [comment]
I have no idea... you're passing --api in the args for stable diffusion, right?

**Comment by TheMeIonGod** [comment]
> I have no idea... you're passing --api in the args for stable diffusion, right?

Correct. Again I am running a bot that runs similar to this one but with stable diffusion. The actual Text-generation-WebUI can use it (Which is running on the same PC as Oobabot but not stable diffusion). I can even open stable diffusion's webui on the PC I am running oobabot on.

**Comment by TheMeIonGod** [comment]
> Ok Now that it sees the stable diffusion it won't actually start the bot when I put --stable-diffusion-url http://192.168.0.23:7900/ into it.

Great... now it is back to not detecting it again.

**Comment by TheMeIonGod** [comment]
Update I see when I tried to connect in Stable Diffusion. The Console pops out this error: During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\stable-diffusion-webui\modules\api\api.py", line 144, in exception_handling
    return await call_next(request)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "H:\stable-diffusion-webui\modules\api\api.py", line 109, in log_and_time
    res: Response = await call_next(req)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "H:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 3 validation errors for Options
response -> ldsr_cached
  value is not None (type=type_error.not_none)
response -> sd_lora
  value is not None (type=type_error.not_none)
response -> depthmap_script_sbsflip
  value is not None (type=type_error.not_none)
