### ISSUE TITLE
set_options     raise StableDiffusionClientError

### ISSUE THREAD

**Issue by FellowChello** [chrisrude/oobabot#42]
Hey, I finally completed a SD Webui install on my server and everything works as intended for the web. But, for some reason the bot is having issues with API:
Traceback (most recent call last):
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\TCHT\oobabooga_windows\installer_files\env\Scripts\oobabot.exe\__main__.py", line 7, in <module>
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\site-packages\oobabot\oobabot.py", line 87, in main
    verify_client(
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\site-packages\oobabot\oobabot.py", line 35, in verify_client
    asyncio.run(try_setup(client))
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\site-packages\oobabot\oobabot.py", line 30, in try_setup
    await client.setup()
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\site-packages\oobabot\sd_client.py", line 273, in setup
    await self.set_options()
  File "C:\TCHT\oobabooga_windows\installer_files\env\lib\site-packages\oobabot\sd_client.py", line 135, in set_options
    raise StableDiffusionClientError(response)
oobabot.sd_client.StableDiffusionClientError: <ClientResponse(http://192.168.100.85:7860/sdapi/v1/options) [500 Internal Server Error]>
<CIMultiDictProxy('Date': 'Mon, 05 Jun 2023 01:58:06 GMT', 'Server': 'uvicorn', 'Content-Length': '172', 'Content-Type': 'application/json')>

I checked the server side and I see this:

![image](https://github.com/chrisrude/oobabot/assets/77192566/ccea89a4-7985-47a1-8fda-34073fd678e7)

**Comment by chrisrude** [comment]
Thanks for the bug report!  I'm curious what version of oobabot you're running.

The reason I ask is that from the specific error message, it seems to be referencing code that's probably several weeks old now.  If that's the case would you be up for upgrading and seeing if the problem persists?  It may will still happen, but it will be easier for me to help track it down if it's from more recent code.

You might want to check out the release notes when upgrading: https://github.com/chrisrude/oobabot/tree/main/docs

Let me know if you're still seeing it!

**Comment by FellowChello** [comment]
Hey, I downloaded the zip file yesterday and then I extracted the content in the root directory of oobabot. 
Any better way to do it, just so i don't mix anything up?

**Comment by chrisrude** [comment]
What version is installed?

I'm asking since the log above was not generated from a recent version... from the line numbers, it would have to have been from v0.1.6 or earlier.

Versions that old had a bug where it would only wait 5 seconds for image generation before throwing this error, which is exactly what is happening in the logs you posted.

This was later fixed in this commit.  I'm fairly optimistic that upgrading will solve the problem you're seeing.
https://github.com/chrisrude/oobabot/commit/8b815362065f6370d7468783ea056cff0aaca440

**Comment by FellowChello** [comment]
OMG, when i did git clone some it pulled it in a different location. Pulled it again in the correct directory and it is working! 
Appreciate the help, Thank you!
