### ISSUE TITLE
AttributeError: module 'discord.utils' has no attribute

### ISSUE THREAD

**Issue by wilburforce666** [chrisrude/oobabot#53]
Traceback (most recent call last):
  File "/home/test/.local/bin/oobabot", line 8, in <module>
    sys.exit(main())
  File "/home/test/.local/lib/python3.10/site-packages/oobabot/oobabot.py", line 375, in main
    oobabot.start()
  File "/home/test/.local/lib/python3.10/site-packages/oobabot/oobabot.py", line 90, in start
    self._begin()
  File "/home/test/.local/lib/python3.10/site-packages/oobabot/oobabot.py", line 140, in _begin
    fancy_logger.init_logging(
  File "/home/test/.local/lib/python3.10/site-packages/oobabot/fancy_logger.py", line 160, in init_logging
    discord_utils.setup_logging(
  File "/home/test/.local/lib/python3.10/site-packages/oobabot/discord_utils.py", line 217, in setup_logging
    discord.utils.setup_logging(**kwargs)
AttributeError: module 'discord.utils' has no attribute 'setup_logging'

getting this error when I try and run bot

**Comment by chrisrude** [comment]
Thanks for the report, and sorry it's not working for you!

I'm curious about what version of discord.py is installed on your system.  Could you please run ` pip list | grep discord` and share the output?

**Comment by chrisrude** [comment]
Haven't heard back, or seen other reports of this, so going to close.  Please reopen if it's still happening!
