### ISSUE TITLE
Empty Response

### ISSUE THREAD

**Issue by ric3b0wl** [chrisrude/oobabot#80]
Not sure what is the reason cause it but doesn't matter starting from the webui or terminal, the bot will receive requests but keep giving the following error: 

```2023-08-22 02:33:46,079 WARNING An empty response was received from Oobabooga.  Please check that the AI is running properly on the Oobabooga server at ws://localhost:5005/.```

**Comment by KungFuFurniture** [comment]
I am having this same issue.  All of a sudden, it worked fine 2 days ago.  It is also not consistent.  I will start receiving messages in discord, but suddenly I won't.  Any thoughts on this would be welcomed. Thanks.

**Comment by jmoney7823956789378** [comment]
read your oobabooga logs for a better idea of what went wrong.

**Comment by KungFuFurniture** [comment]
Wow quick response, thanks!  Below is all the info I get.  Which is the same as above.  

2023-10-20 16:30:41,902 WARNING An empty response was received from Oobabooga. Please check that the AI is running properly on the Oobabooga server at ws://localhost:5005.

Either I can't read the logs, or I just can't find the right one.  NOOB.

**Comment by jmoney7823956789378** [comment]
that's the output from oobabot, you'll need to look around for what the actual oobabooga server is saying.

**Comment by Phixia** [comment]
Having a similar issue the response I get from server is:

```
connection handler failed
Traceback (most recent call last):
  File "C:\Users\redacted\text-generation-webui\installer_files\env\Lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "C:\Users\redacted\text-generation-webui\installer_files\env\Lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "C:\Users\redacted\text-generation-webui\extensions\api\streaming_api.py", line 92, in _handle_connection
    await _handle_stream_message(websocket, message)
  File "C:\Users\redacted\text-generation-webui\extensions\api\util.py", line 155, in api_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\redacted\text-generation-webui\extensions\api\streaming_api.py", line 37, in _handle_stream_message
    for a in generator:
  File "C:\Users\redacted\text-generation-webui\modules\text_generation.py", line 32, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "C:\Users\redacted\text-generation-webui\modules\text_generation.py", line 88, in _generate_reply
    for reply in generate_func(question, original_question, seed, state, stopping_strings, is_chat=is_chat):
  File "C:\Users\redacted\text-generation-webui\modules\text_generation.py", line 293, in generate_reply_HF
    if isinstance(state['sampler_priority'], list) and len(state['sampler_priority']) > 0:
                  ~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'sampler_priority'
```
I'm running a new build of oobabooga but I am loading the legacy API per https://github.com/chrisrude/oobabot/issues/83

My oobabot is connecting to discord and monitoring my channels there but it is unable to generate responses to wake words.

**Comment by jmoney7823956789378** [comment]
@Phixia unfortunately the legacy API seems to have been made completely unsupported, so it no longer works without heavy modification.
alternatively, I have done my best to write a functioning method of connecting via the openai-like api instead:
https://github.com/jmoney7823956789378/oobabot
you may need to re-generate your config.yml in order to see the new options.

**Comment by Phixia** [comment]
Thanks much I'll give it a go
